spring:
  application:
    name: Desafio Leônico
  datasource:
    url: jdbc:mysql://localhost:3306/desleo?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
    name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
logger:
  root: DEBUG